package template;

public enum StatType {
    PHYSICAL_DAMAGE(0, "Kerusakan fisik", false),
    ICE_DAMAGE(1, "Kerusakan es", false),
    FIRE_DAMAGE(2, "Kerusakan api", false),
    LIGHTNING_DAMAGE(3, "Kerusakan listrik", false),
    POISON_DAMAGE(4, "Kerusakan racun", false),
    DARK_DAMAGE(5, "Kerusakan kegelapan", false),
    LIGHT_DAMAGE(6, "Kerusakan cahaya", false),
    PHYSICAL_DAMAGE_PERCENT(7, "+ Kerusakan fisik", true),
    ICE_DAMAGE_PERCENT(8, "+ Kerusakan es", true),
    FIRE_DAMAGE_PERCENT(9, "+ Kerusakan api", true),
    LIGHTNING_DAMAGE_PERCENT(10, "+ Kerusakan listrik", true),
    POISON_DAMAGE_PERCENT(11, "+ Kerusakan racun", true),
    DARK_DAMAGE_PERCENT(12, "+ Kerusakan kegelapan", true),
    LIGHT_DAMAGE_PERCENT(13, "+ Kerusakan cahaya", true),
    DEFENSE(14, "Pertahanan", false),
    DEFENSE_PERCENT(15, "+ Pertahanan", true),
    PHYSICAL_RESISTANCE(16, "Resistensi fisik", true),
    ICE_RESISTANCE(17, "Resistensi es", true),
    FIRE_RESISTANCE(18, "Resistensi api", true),
    LIGHTNING_RESISTANCE(19, "Resistensi listrik", true),
    POISON_RESISTANCE(20, "Resistensi racun", true),
    DARK_RESISTANCE(21, "Resistensi kegelapan", false),
    LIGHT_RESISTANCE(22, "Resistensi cahaya", false),
    STRENGTH(23, "+ Kekuatan", false),
    AGILITY(24, "+ Keluwesan", false),
    STAMINA(25, "+ Stamina", false),
    SPIRIT(26, "+ Roh/Mental", false),
    HP_PERCENT(27, "+ HP (Darah)", true),
    MANA_PERCENT(28, "+ Mana", true),
    AUTO_HP_RECOVERY(29, "Pemulihan HP otomatis", true),
    AUTO_MANA_RECOVERY(30, "Pemulihan Mana otomatis", true),
    HP_DRAIN(31, "Kemampuan hisap HP", true),
    MANA_DRAIN(32, "Kemampuan hisap Mana", true),
    CRITICAL_HIT(33, "Serangan kritis", true),
    DODGE(34, "Menghindar", true),
    DAMAGE_REFLECTION(35, "Refleksi kerusakan", true),
    ARMOR_PENETRATION(36, "Penetrasi Armor", true),
    ATTACK_SKILL_BONUS(37, "+ Skill serangan", false),
    DEFENSE_SKILL_BONUS(38, "+ Skill pertahanan", false),
    SPECIAL_SKILL(39, "Skill khusus", false),
    BASE_DAMAGE(40, "Kerusakan dasar", false),
    RAGE_RATE(41, "Tingkat kemarahan", true),
    RAGE_DURATION(42, "Durasi kemarahan", false),
    PET_HATCH(43, "Tempatkan telur di kandang hewan untuk dierami", false),
    MANA_RESTORE(44, "Pulihkan mana", true),
    SLEEP(45, "Tidurkan", false),
    STUN(46, "Menyebabkan pusing/setrum", false),
    HP_RESTORE(47, "Pulihkan HP", true),
    DAMAGE_BONUS(48, "+ Kerusakan", false),
    EXP_BONUS(49, "+ Exp", false),
    SPEED_BONUS(50, "+ Kecepatan", false),
    EXP_BONUS_PERCENT(51, "+ Exp tambahan", true),
    GOLD_BONUS(52, "+ Emas", true),
    THIEF_CLASS(53, "Perampok", false),
    KNIGHT_CLASS(54, "Ksatria", false),
    MERCHANT_CLASS(55, "P.dagang", false),
    DARK_DAMAGE_RATE(56, "Tingkat kerusakan kegelapan", true),
    LIGHT_DAMAGE_RATE(57, "Tingkat kerusakan cahaya", true),
    SOCKET_1(58, "Lubang 1", false),
    SOCKET_2(59, "Lubang 2", false),
    SOCKET_3(60, "Lubang 3", false),
    ENCHANTMENT(61, "Jampi-jampi", false),
    GHOST_RESISTANCE(62, "Resistensi hantu", true),
    TRANSFORMATION(63, "Transformasi", true),
    LIGHT_DAMAGE_BONUS(64, "+ K.rusakan cahaya", true),
    DARK_DAMAGE_BONUS(65, "+ K.rusakan kegelapan", true),
    FREEZE(66, "Membeku", true),
    FROZEN(67, "Kebekuan", true),
    EXTENSION(68, "Perpanjangan", false),
    DEFORMATION(69, "Deformasi", true),
    SELL_PRICE(70, "Harga jual", false),
    EFFECT(71, "Efek", false),
    DARK_CRITICAL_RATE(72, "Tingkat kritis kegelapan", true),
    DARK_CRITICAL_DAMAGE(73, "+ K.rusakan kritis kegelapan", true),
    LIGHT_CRITICAL_RATE(74, "Tingkat kritis cahaya", true),
    LIGHT_CRITICAL_DAMAGE(75, "+ K.rusakan kritis cahaya", true),
    FIRE_BURN_RATE(76, "Tingkat luka bakar api", true),
    FIRE_BURN_DAMAGE(77, "-Luka bakar api", false),
    ICE_BURN_RATE(78, "Tingkat luka bakar dingin", true),
    ICE_BURN_DAMAGE(79, "Luka bakar dingin", false),
    DARK_ARMOR(80, "Armor kegelapan", true),
    INVISIBILITY(81, "Tak terlihat", false),
    INVISIBILITY_RATE(82, "Tingkat tak terlihat", true),
    COOLDOWN_REDUCTION_RATE(83, "Tingkat pengurangan Cooldown", true),
    COOLDOWN_REDUCTION(84, "- Pengurangan Cooldown", false),
    MAGIC_SHIELD_RATE(85, "Tingkat perisai sihir", true),
    MAGIC_SHIELD(86, "- Perisai sihir", false),
    CONFUSION_RATE(87, "Tingkat kebingungan", true),
    CONFUSION(88, "- Kebingungan", false),
    ALL_RESISTANCE(89, "Resistensi semua", true),
    PHYSICAL_DAMAGE_REDUCTION(90, "Pengurangan k.rusakan fisik", true),
    ICE_DAMAGE_REDUCTION(91, "Pengurangan k.rusakan es", true),
    FIRE_DAMAGE_REDUCTION(92, "Pengurangan k.rusakan api", true),
    LIGHTNING_DAMAGE_REDUCTION(93, "Pengurangan k.rusakan listrik", true),
    POISON_DAMAGE_REDUCTION(94, "Pengurangan k.rusakan racun", true),
    ALL_RESISTANCE_REDUCTION(95, "Pengurangan resistensi semua", true),
    HIDDEN_LINES(96, "Jumlah baris tersembunyi yang mungkin", false),
    DEEP_WOUND_RATE(97, "Tingkat luka dalam", true),
    DEEP_WOUND(98, "-Luka dalam", false),
    ACCURACY(99, "Akurasi", true),
    SKY_RAIN(100, "Hujan langit", false),
    MAGIC_RESISTANCE(101, "Resistensi sihir", false),
    ABSORPTION(102, "Penyerapan", true),
    RECOVERY(103, "Pemulihan", true),
    HP_LOWER(104, "- HP lebih rendah", true),
    HP_RECOVERY(105, "- HP pulih", true),
    STORM(106, "Badai", true),
    CRITICAL_DAMAGE(107, "+K.rusakan kritis", true),
    SPACE(108, "Ruang", false),
    REBIRTH(109, "Kelahiran kembali", false),
    CLONE(110, "Kloning", false),
    POWER(111, "Kekuatan", true),
    ARENA_POINTS(112, "Poin Arena", false),
    MAX_HP_DAMAGE(113, "Kerusakan MaxHP", true),
    TOTAL_TARGET(114, "Total target", false),
    PERMANENT(115, "permanen", false),
    COMBO(116, "Kombo", true),
    DARK_GUARDIAN(117, "Penjaga kegelapan", false),
    TRANSFORMATION_SKILL(118, "Ilmu transformasi", false),
    PASSIVE_REDUCTION(119, "Pengurangan pasif", false),
    NEUTRALIZATION_SKILL(120, "Ilmu penetralan", false),
    GEM_REWARD_POINTS(121, "Poin hadiah permata", false),
    NO_EXP_BONUS(122, "Tidak ada penambahan Exp", true),
    AUTO_ATTACK_DURATION(123, "Durasi serangan otomatis", false),
    JEWELRY_TRADE(124, "Digunakan untuk perdagangan perhiasan", false),
    WEAPON_TRADE(125, "Digunakan untuk perdagangan senjata", false),
    COSTUME_TRADE(126, "Digunakan untuk perdagangan kostum", false),
    MEDAL_TRADE(127, "Digunakan untuk perdagangan medali", false),
    PURE_DAMAGE(128, "Kerusakan murni", true),
    DURABILITY(129, "Daya tahan", true),
    LUCK_RATE(130, "Tingkat keberuntungan", true),
    EXPLOSION(131, "Ledakan", true),
    FLASH(132, "Kilatan", true),
    FIRE_IMMUNITY(133, "Kebal k.rusakan api", true),
    POISON_IMMUNITY(134, "Kebal k.rusakan racun", true),
    PHYSICAL_IMMUNITY(135, "Kebal k.rusakan fisik", true),
    ICE_IMMUNITY(136, "Kebal k.rusakan es", true),
    LIGHTNING_IMMUNITY(137, "Kebal k.rusakan listrik", true),
    HP_DRAIN_AFTER_3_ATTACKS(138, "Hisap HP setelah 3 serangan", true),
    BRUTAL(139, "Brutal", true),
    BLIND(140, "Buta", true),
    BURN_20_SEC_COOLDOWN(141, "Bakar dalam 20 detik, cooldown", false),
    PROTECTIVE_ARMOR(142, "Armor pelindung", true),
    EXPLOSION_2(143, "Ledakan", true),
    FLASH_2(144, "Kilatan", true),
    FIRE_IMMUNITY_2(145, "Kebal k.rusakan api", true),
    POISON_IMMUNITY_2(146, "Kebal k.rusakan racun", true),
    PHYSICAL_IMMUNITY_2(147, "Kebal k.rusakan fisik", true),
    ICE_IMMUNITY_2(148, "Kebal k.rusakan es", true),
    LIGHTNING_IMMUNITY_2(149, "Kebal k.rusakan listrik", true),
    HP_DRAIN_2(150, "Hisap HP", true),
    BRUTAL_2(151, "Brutal", true),
    BLIND_2(152, "Buta", true),
    BURN_2(153, "Bakar", false),
    PROTECTIVE_ARMOR_2(154, "Armor pelindung", true),
    PURE_DAMAGE_2(155, "Kerusakan murni", true),
    QUALITY(156, "Kualitas", true),
    DOUBLE_REWARD(157, "Gandakan hadiah saat menggunakan", true),
    FREE_PURCHASE(158, "Pembelian gratis", true),
    ANTI_KILL(159, "Anti-pembunuhan", true),
    LIGHTNING_PUNISHMENT(160, "Hukuman petir", true),
    HELL_FIRE(161, "Api neraka", true),
    EXTENSION_COUNT(162, "Jumlah perpanjangan", false),
    PET_DURATION(163, "Durasi pet", false),
    PARALYSIS(164, "Lumpuh", true),
    PARALYSIS_2(165, "Lumpuh", true),
    STUPID(166, "Bodoh", true),
    STUPID_2(167, "Bodoh", true),
    IMMUNITY_5_SEC_COOLDOWN(168, "Kebal dalam 5 detik, cooldown", false),
    IMMUNITY_5_SEC_COOLDOWN_2(169, "Kebal dalam 5 detik, cooldown", false),
    ACCURACY_2(170, "Akurasi", true),
    PLATINUM_ARMOR(171, "Armor platinum", true),
    PLATINUM_ARMOR_2(172, "Armor platinum", true),
    ANGEL_ARMOR(173, "Armor malaikat", true),
    ANGEL_ARMOR_2(174, "Armor malaikat", true),
    GUARDIAN_ARMOR(175, "Armor penjaga", true),
    GUARDIAN_ARMOR_2(176, "Armor penjaga", true),
    GREEN_STAR_TRADE(177, "Digunakan untuk perdagangan barang bintang hijau", false),
    PARAGON_POINTS(178, "Poin Paragon", false),
    PARAGON_LEVEL(179, "Tingkat Paragon", false),
    DIZZY(180, "Pusing", true),
    GEM_RECHARGE_POINTS(181, "Poin isi ulang permata", false),
    GEM_USAGE_POINTS(182, "Poin penggunaan permata", false),
    WAR_ACHIEVEMENT_POINTS(183, "Poin pencapaian perang", false),
    CALL_LIGHTNING(184, "Panggil petir", true),
    DOMINATION(185, "Dominasi", true),
    BONE_ARMOR(186, "Armor tulang", true),
    CHRISTMAS_GIFT_RATE(187, "Tingkat hadiah natal", true),
    CHRISTMAS_GIFT(188, "-Hadiah natal", false),
    FIRE_ARMOR(189, "Armor api", true),
    PET_HATCH_2(190, "Tempatkan telur di kandang hewan untuk dierami", false);

    public final int id;
    public final String name;
    public final boolean isPercent;

    StatType(int id, String name, boolean isPercent) {
        this.id = id;
        this.name = name;
        this.isPercent = isPercent;
    }

    public static StatType getById(int id) {
        for (StatType stat : values()) {
            if (stat.id == id) return stat;
        }
        return null;
    }
}